name: React deployment
on:
  push:
    branches:
      - main
      - dev-*
      - feat-*
      - feat/**
    paths-ignore:
    - '.github/workflows/*'
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main
      - dev-*
      - feat-*
      - feat/**
  issues:
    types:
      - opened
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run test
        run: npm run test
      - name: Run build
        run: npm run build
      - name: Deploy the app
        run: echo "Deploying ..."